apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-driver
  labels:
    app: main-driver
spec:
  selector:
    matchLabels:
      app: main-driver
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: main-driver
    spec:
      containers:
        - image: shihsunl/14848_proj_driver:ssh_ver
          imagePullPolicy: Always
          name: main-driver_ssh
          env:
            - name: SPARK_SERVICE_URL
              value: "http://spark-service"
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 8080
