apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-driver
  labels:
    app: main-driver
spec:
  selector:
    matchLabels:
      app: main-driver
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: main-driver
    spec:
      containers:
        - image: shihsunl/14848_proj_driver
          imagePullPolicy: Always
          name: main-driver
          ports:
            - containerPort: 80
