apiVersion: v1
kind: Service
metadata:
  name: main-driver-ssh-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 22
    protocol: TCP
    targetPort: 22
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: main-driver-ssh
